apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  labels:
    app: guestbook
    tier: front-end

spec:
  type: NodePort
#  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: guestbook
    tier: front-end
