apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: test-container
    image: mysql:8.0.33
    envFrom:
    - configMapRef:
        name: mysql-env-var
  restartPolicy: Never
