apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic
  labels:
    tipo: "desarrollo"

spec:
  selector: #Permite seleccionar un conjunto de objetos que cumplan las condiciones
    matchLabels:
      app: elastic

  replicas: 2 #Indica al controlador que cree 2 pods
  strategy:
    type: RollingUpdate
  minReadySeconds: 2
  template: #plantilla que define los containers
    metadata:
      labels:
        app: elastic

    spec:
      containers:
      - name: elastic
        image: elasticsearch:8.8.1
        ports:
        - containerPort: 9200


